# Phase 3: Data Preparation

**CRISP-DM Phase Description:**  
This phase covers all activities to construct the final dataset from the initial raw data. Data preparation tasks are likely to be performed multiple times, and not in any prescribed order. This is typically the longest and most time-consuming phase of the CRISP-DM lifecycle.

---

In [16]:
# Standard library imports for this phase
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
%matplotlib inline

In [17]:
# Load the dataset from Phase 2
DATA_PATH = "../data/Metro_Interstate_Traffic_Volume.csv"   # change filename if needed

df = pd.read_csv(DATA_PATH)

print(f"Loaded dataset: {df.shape[0]} rows x {df.shape[1]} columns")
display(df.head())
print("\nColumns:")
print(df.columns.tolist())

Loaded dataset: 48204 rows x 9 columns

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume
0,NaN,288.28,0.0,0.0,40,Clouds,scattered clouds,2012-10-02 09:00:00,5545
1,NaN,289.36,0.0,0.0,75,Clouds,broken clouds,2012-10-02 10:00:00,4516
2,NaN,289.58,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 11:00:00,4767
3,NaN,290.13,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 12:00:00,5026
4,NaN,291.14,0.0,0.0,75,Clouds,broken clouds,2012-10-02 13:00:00,4918

Columns:
['holiday', 'temp', 'rain_1h', 'snow_1h', 'clouds_all', 'weather_main', 'weather_description', 'date_time', 'traffic_volume']

---
### Task 1: Select Data

Decide on the data to be used for analysis. Consider which columns (features) and rows (records) to include or exclude based on:

- **Relevance:** Does this feature contribute to the data mining goal?
- **Data Quality:** Is the quality of this feature sufficient (e.g., too many missing values)?
- **Technical Constraints:** Are there limitations on data volume or specific feature types?

**Output:** A rationale for inclusion/exclusion of data, and the resulting subset.

**Instructions:** Select the columns and rows relevant to your analysis goal. Document your reasoning.

In [18]:
# Task 1: Select relevant columns and document reasons for keeping/dropping them

columns_to_keep = [
    "holiday",
    "temp",
    "rain_1h",
    "snow_1h",
    "clouds_all",
    "weather_main",
    "weather_description",
    "date_time",
    "traffic_volume"
]

keep_reasons = {
    "holiday": "May capture abnormal traffic patterns on public holidays.",
    "temp": "Represents general weather conditions that may influence travel behaviour.",
    "rain_1h": "Rain can affect road conditions and travel demand.",
    "snow_1h": "Snow can strongly affect traffic flow and congestion.",
    "clouds_all": "Captures overall sky conditions that may relate to weather-driven travel behaviour.",
    "weather_main": "High-level weather category useful for modelling.",
    "weather_description": "Provides more detailed weather information than weather_main.",
    "date_time": "Essential for extracting time-based features such as hour, month, and day of week.",
    "traffic_volume": "Target variable to be predicted."
}

columns_to_drop = ["temp_min", "temp_max"]
drop_reasons = {
    "temp_min": "Dropped because it overlaps with the main temperature variable and may add redundancy without much extra predictive value.",
    "temp_max": "Dropped because it overlaps with the main temperature variable and may add redundancy without much extra predictive value."
}

df_selected = df[columns_to_keep].copy()

keep_report = pd.DataFrame({
    "Column Kept": list(keep_reasons.keys()),
    "Reason": list(keep_reasons.values())
})

drop_report = pd.DataFrame({
    "Column Dropped": list(drop_reasons.keys()),
    "Reason": list(drop_reasons.values())
})

print("Selected columns:")
display(keep_report)

print("Dropped columns:")
display(drop_report)

print(f"Shape after column selection: {df_selected.shape}")
display(df_selected.head())

Selected columns:

           Column Kept                                             Reason
0              holiday  May capture abnormal traffic patterns on publi...
1                 temp  Represents general weather conditions that may...
2              rain_1h  Rain can affect road conditions and travel dem...
3              snow_1h  Snow can strongly affect traffic flow and cong...
4           clouds_all  Captures overall sky conditions that may relat...
5         weather_main  High-level weather category useful for modelling.
6  weather_description  Provides more detailed weather information tha...
7            date_time  Essential for extracting time-based features s...
8       traffic_volume                   Target variable to be predicted.

Dropped columns:

  Column Dropped                                             Reason
0       temp_min  Dropped because it overlaps with the main temp...
1       temp_max  Dropped because it overlaps with the main temp...

Shape after column selection: (48204, 9)

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume
0,NaN,288.28,0.0,0.0,40,Clouds,scattered clouds,2012-10-02 09:00:00,5545
1,NaN,289.36,0.0,0.0,75,Clouds,broken clouds,2012-10-02 10:00:00,4516
2,NaN,289.58,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 11:00:00,4767
3,NaN,290.13,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 12:00:00,5026
4,NaN,291.14,0.0,0.0,75,Clouds,broken clouds,2012-10-02 13:00:00,4918

In [19]:
# Optional: Filter rows based on specific criteria
# Example: Remove rows where a critical field is missing or filter by a condition


before_rows = len(df_selected)

# Remove rows where the target or datetime is missing
df_selected = df_selected.dropna(subset=['date_time', 'traffic_volume'])

after_rows = len(df_selected)

print(f"Rows before filtering: {before_rows}")
print(f"Rows after filtering:  {after_rows}")
print(f"Rows removed:          {before_rows - after_rows}")

Rows before filtering: 48204
Rows after filtering:  48204
Rows removed:          0

---
### Task 2: Clean Data

Raise data quality to the level required by the selected analysis techniques. Cleaning activities include:

- **Handle Missing Values:** Impute missing values (mean, median, mode, forward/backward fill) or remove rows/columns with excessive missing data.
- **Correct Errors:** Fix inaccurate or corrupted data entries.
- **Remove Duplicates:** Eliminate exact or near-duplicate records.
- **Handle Outliers:** Decide how to treat extreme values (keep, cap, transform, or remove).

**Instructions:** Apply appropriate cleaning techniques to address the data quality issues identified in Phase 2, Task 4.

In [31]:
# TODO: Handle missing values.
# Choose an appropriate strategy for each column.

# Example strategies:
# df_clean = df_selected.copy()

# Strategy 1: Impute numerical columns with the median
# numerical_cols = df_clean.select_dtypes(include=np.number).columns
# df_clean[numerical_cols] = df_clean[numerical_cols].fillna(df_clean[numerical_cols].median())

# Strategy 2: Impute categorical columns with the mode
# categorical_cols = df_clean.select_dtypes(include='object').columns
# for col in categorical_cols:
#     df_clean[col] = df_clean[col].fillna(df_clean[col].mode()[0])

# Strategy 3: Drop rows/columns with too many missing values
# df_clean = df_clean.dropna(thresh=len(df_clean) * 0.5, axis=1)  # Drop cols with >50% missing

# print(f"Missing values remaining: {df_clean.isnull().sum().sum()}")


df_clean = df_selected.copy()

print("Missing values before cleaning:")
print(df_clean.isnull().sum())

# Numerical columns -> fill with median
numerical_cols = ['temp', 'rain_1h', 'snow_1h', 'clouds_all', 'traffic_volume']
for col in numerical_cols:
    df_clean[col] = df_clean[col].fillna(df_clean[col].median())

# Categorical columns -> fill with mode
categorical_cols = ['holiday', 'weather_main', 'weather_description']
for col in categorical_cols:
    df_clean[col] = df_clean[col].fillna(df_clean[col].mode()[0])

print("\nMissing values after cleaning:")
print(df_clean.isnull().sum())

print("\nCleaning Insight:")
print("- Numerical columns were imputed with the median because it is robust to skewed values and outliers.")
print("- Categorical columns were imputed with the mode to preserve the most frequent category.")
print("- This approach keeps more observations and avoids unnecessary data loss.")

Missing values before cleaning:
holiday                48143
temp                       0
rain_1h                    0
snow_1h                    0
clouds_all                 0
weather_main               0
weather_description        0
date_time                  0
traffic_volume             0
dtype: int64

Missing values after cleaning:
holiday                0
temp                   0
rain_1h                0
snow_1h                0
clouds_all             0
weather_main           0
weather_description    0
date_time              0
traffic_volume         0
dtype: int64

Cleaning Insight:
- Numerical columns were imputed with the median because it is robust to skewed values and outliers.
- Categorical columns were imputed with the mode to preserve the most frequent category.
- This approach keeps more observations and avoids unnecessary data loss.

In [21]:
# TODO: Remove duplicate records.

before = len(df_clean)
duplicates_before = df_clean.duplicated().sum()

df_clean = df_clean.drop_duplicates()

after = len(df_clean)
duplicates_after = df_clean.duplicated().sum()

print(f"Duplicate rows before removal: {duplicates_before}")
print(f"Rows removed: {before - after}")
print(f"Remaining rows: {after}")
print(f"Duplicate rows after removal: {duplicates_after}")

Duplicate rows before removal: 17
Rows removed: 17
Remaining rows: 48187
Duplicate rows after removal: 0

In [32]:
# TODO: Handle outliers.
# Choose a strategy: capping (winsorizing), removing, or transforming.


# Task 2: Handle outliers using IQR capping for weather-related numerical columns

def cap_outliers_iqr(dataframe, column):
    Q1 = dataframe[column].quantile(0.25)
    Q3 = dataframe[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    dataframe[column] = dataframe[column].clip(lower=lower_bound, upper=upper_bound)
    return dataframe

outlier_cols = ['temp', 'rain_1h', 'snow_1h', 'clouds_all']

for col in outlier_cols:
    df_clean = cap_outliers_iqr(df_clean, col)

print("Outlier capping completed for:")
print(outlier_cols)

display(df_clean[outlier_cols].describe())

print("\nOutlier Handling Insight:")
print("- Outliers were capped using the IQR method instead of removing rows to avoid losing potentially useful observations.")
print("- Weather-related numerical features were prioritised because extreme values there can distort model learning.")
print("- The target variable 'traffic_volume' was not capped so the real prediction target remains unchanged.")

Outlier capping completed for:
['temp', 'rain_1h', 'snow_1h', 'clouds_all']

               temp  rain_1h  snow_1h    clouds_all
count  48204.000000  48204.0  48204.0  48204.000000
mean     281.256217      0.0      0.0     49.362231
std       12.720405      0.0      0.0     39.015750
min      242.691000      0.0      0.0      0.000000
25%      272.160000      0.0      0.0      1.000000
50%      282.450000      0.0      0.0     64.000000
75%      291.806000      0.0      0.0     90.000000
max      310.070000      0.0      0.0    100.000000

Outlier Handling Insight:
- Outliers were capped using the IQR method instead of removing rows to avoid losing potentially useful observations.
- Weather-related numerical features were prioritised because extreme values there can distort model learning.
- The target variable 'traffic_volume' was not capped so the real prediction target remains unchanged.

---
### Task 3: Construct Data (Feature Engineering)

This task involves creating new attributes (features) derived from existing ones that may be more useful for modelling. Common techniques include:

- **Derived Attributes:** Create new features from existing ones (e.g., extracting `year`, `month`, `day` from a datetime column; computing `total_spend = price * quantity`).
- **Binning / Discretisation:** Convert continuous variables into categorical bins (e.g., age groups).
- **Encoding Categorical Variables:** Convert categorical features into numerical representations (e.g., one-hot encoding, label encoding).
- **Scaling / Normalisation:** Scale numerical features to a common range (e.g., Min-Max scaling, Standardisation).

**Instructions:** Create new features or transform existing ones to improve model performance.

In [34]:
# Task 3: Construct data - create new features that add insight and modelling value

df_clean["date_time"] = pd.to_datetime(df_clean["date_time"])

# Standard calendar features
df_clean["year"] = df_clean["date_time"].dt.year
df_clean["month"] = df_clean["date_time"].dt.month
df_clean["day"] = df_clean["date_time"].dt.day
df_clean["hour"] = df_clean["date_time"].dt.hour
df_clean["day_of_week"] = df_clean["date_time"].dt.dayofweek
df_clean["is_weekend"] = df_clean["day_of_week"].isin([5, 6]).astype(int)

# Extra insight-driven features
df_clean["is_rush_hour"] = df_clean["hour"].isin([7, 8, 9, 16, 17, 18]).astype(int)
df_clean["part_of_day"] = pd.cut(
    df_clean["hour"],
    bins=[-1, 5, 11, 17, 21, 23],
    labels=["night", "morning", "afternoon", "evening", "late_evening"]
)
df_clean["season"] = df_clean["month"] % 12 // 3 + 1
season_map = {1: "winter", 2: "spring", 3: "summer", 4: "autumn"}
df_clean["season"] = df_clean["season"].map(season_map)

new_feature_report = pd.DataFrame({
    "New Feature": [
        "year", "month", "day", "hour", "day_of_week", "is_weekend",
        "is_rush_hour", "part_of_day", "season"
    ],
    "Purpose": [
        "Captures long-term variation.",
        "Captures seasonal/monthly effects.",
        "Captures within-month variation.",
        "Captures intraday traffic pattern.",
        "Separates weekdays from weekends structurally.",
        "Explicit weekend indicator.",
        "Captures expected commuting peaks.",
        "Groups hours into interpretable time blocks.",
        "Captures broader seasonal weather/travel behaviour."
    ]
})

print("New derived features created:")
display(new_feature_report)
display(df_clean.head())

New derived features created:

    New Feature                                            Purpose
0          year                      Captures long-term variation.
1         month                 Captures seasonal/monthly effects.
2           day                   Captures within-month variation.
3          hour                 Captures intraday traffic pattern.
4   day_of_week     Separates weekdays from weekends structurally.
5    is_weekend                        Explicit weekend indicator.
6  is_rush_hour                 Captures expected commuting peaks.
7   part_of_day       Groups hours into interpretable time blocks.
8        season  Captures broader seasonal weather/travel behav...

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume,year,month,day,hour,day_of_week,is_weekend,is_rush_hour,part_of_day,season
0,Labor Day,288.28,0.0,0.0,40,Clouds,scattered clouds,2012-10-02 09:00:00,5545,2012,10,2,9,1,0,1,morning,autumn
1,Labor Day,289.36,0.0,0.0,75,Clouds,broken clouds,2012-10-02 10:00:00,4516,2012,10,2,10,1,0,0,morning,autumn
2,Labor Day,289.58,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 11:00:00,4767,2012,10,2,11,1,0,0,morning,autumn
3,Labor Day,290.13,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 12:00:00,5026,2012,10,2,12,1,0,0,afternoon,autumn
4,Labor Day,291.14,0.0,0.0,75,Clouds,broken clouds,2012-10-02 13:00:00,4918,2012,10,2,13,1,0,0,afternoon,autumn

In [35]:
# Encode categorical variables using one-hot encoding

categorical_cols = ["holiday", "weather_main", "weather_description", "part_of_day", "season"]

df_clean = pd.get_dummies(df_clean, columns=categorical_cols, drop_first=True)

encoding_report = pd.DataFrame({
    "Encoded Column": categorical_cols,
    "Reason": [
        "One-hot encoded because categories are nominal, not ordered.",
        "One-hot encoded because categories are nominal, not ordered.",
        "One-hot encoded because categories are nominal, not ordered.",
        "One-hot encoded because categories are nominal, not ordered.",
        "One-hot encoded because categories are nominal, not ordered."
    ]
})

display(encoding_report)
display(df_clean.head())

        Encoded Column                                             Reason
0              holiday  One-hot encoded because categories are nominal...
1         weather_main  One-hot encoded because categories are nominal...
2  weather_description  One-hot encoded because categories are nominal...
3          part_of_day  One-hot encoded because categories are nominal...
4               season  One-hot encoded because categories are nominal...

,temp,rain_1h,snow_1h,clouds_all,date_time,traffic_volume,year,month,day,hour,day_of_week,is_weekend,is_rush_hour,holiday_Columbus Day,holiday_Independence Day,holiday_Labor Day,holiday_Martin Luther King Jr Day,holiday_Memorial Day,holiday_New Years Day,holiday_State Fair,holiday_Thanksgiving Day,holiday_Veterans Day,holiday_Washingtons Birthday,weather_main_Clouds,weather_main_Drizzle,weather_main_Fog,weather_main_Haze,weather_main_Mist,weather_main_Rain,weather_main_Smoke,weather_main_Snow,weather_main_Squall,weather_main_Thunderstorm,weather_description_Sky is Clear,weather_description_broken clouds,weather_description_drizzle,weather_description_few clouds,weather_description_fog,weather_description_freezing rain,weather_description_haze,weather_description_heavy intensity drizzle,weather_description_heavy intensity rain,weather_description_heavy snow,weather_description_light intensity drizzle,weather_description_light intensity shower rain,weather_description_light rain,weather_description_light rain and snow,weather_description_light shower snow,weather_description_light snow,weather_description_mist,weather_description_moderate rain,weather_description_overcast clouds,weather_description_proximity shower rain,weather_description_proximity thunderstorm,weather_description_proximity thunderstorm with drizzle,weather_description_proximity thunderstorm with rain,weather_description_scattered clouds,weather_description_shower drizzle,weather_description_shower snow,weather_description_sky is clear,weather_description_sleet,weather_description_smoke,weather_description_snow,weather_description_thunderstorm,weather_description_thunderstorm with drizzle,weather_description_thunderstorm with heavy rain,weather_description_thunderstorm with light drizzle,weather_description_thunderstorm with light rain,weather_description_thunderstorm with rain,weather_description_very heavy rain,part_of_day_morning,part_of_day_afternoon,part_of_day_evening,part_of_day_late_evening,season_spring,season_summer,season_winter
0,288.28,0.0,0.0,40,2012-10-02 09:00:00,5545,2012,10,2,9,1,0,1,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
1,289.36,0.0,0.0,75,2012-10-02 10:00:00,4516,2012,10,2,10,1,0,0,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
2,289.58,0.0,0.0,90,2012-10-02 11:00:00,4767,2012,10,2,11,1,0,0,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
3,290.13,0.0,0.0,90,2012-10-02 12:00:00,5026,2012,10,2,12,1,0,0,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
4,291.14,0.0,0.0,75,2012-10-02 13:00:00,4918,2012,10,2,13,1,0,0,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False

In [25]:
# TODO: Scale / normalise numerical features if required.

# from sklearn.preprocessing import StandardScaler, MinMaxScaler

# scaler = StandardScaler()  # or MinMaxScaler()
# cols_to_scale = ['feature_1', 'feature_2']
# df_clean[cols_to_scale] = scaler.fit_transform(df_clean[cols_to_scale])


# Task 3: Scaling / normalisation

# For this project, scaling is not applied at this stage.
# Tree-based models do not require scaling, and scaling can also be done later
# after the train-test split in Phase 4 to avoid data leakage.

print("No scaling applied in Phase 3.")
print("Reason: scaling will be handled later if required by the chosen model.")

No scaling applied in Phase 3.
Reason: scaling will be handled later if required by the chosen model.

---
### Task 4: Integrate Data

If your project uses multiple data sources, this task involves merging or combining them into a single, unified dataset. Activities include:

- **Merging Tables:** Join datasets on common keys (e.g., using `pd.merge()`).
- **Appending Records:** Concatenate datasets with the same structure (e.g., using `pd.concat()`).
- **Aggregation:** Summarise data at a different level of granularity.

**Instructions:** If using multiple data sources, merge or concatenate them below. If your project uses a single dataset, document that here and proceed to the next task.

In [26]:
# TODO: Integrate data from multiple sources (if applicable).

# Example: Merge two DataFrames on a common key
# df_secondary = pd.read_csv('path/to/secondary_data.csv')
# df_integrated = pd.merge(df_clean, df_secondary, on='common_key', how='left')

# Example: Concatenate DataFrames with the same structure
# df_integrated = pd.concat([df_part1, df_part2], ignore_index=True)

# If using a single source, simply continue:
# df_integrated = df_clean.copy()
# print(f"Integrated dataset shape: {df_integrated.shape}")


# This project uses a single dataset, so no merging or concatenation is required.
df_integrated = df_clean.copy()

print("This project uses a single data source.")
print(f"Integrated dataset shape: {df_integrated.shape}")
display(df_integrated.head())

This project uses a single data source.
Integrated dataset shape: (48187, 18)

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume,year,month,day,hour,day_of_week,is_weekend,is_rush_hour,part_of_day,season
0,3,288.28,0.0,0.0,40,1,24,2012-10-02 09:00:00,5545,2012,10,2,9,1,0,1,3,0
1,3,289.36,0.0,0.0,75,1,2,2012-10-02 10:00:00,4516,2012,10,2,10,1,0,0,3,0
2,3,289.58,0.0,0.0,90,1,19,2012-10-02 11:00:00,4767,2012,10,2,11,1,0,0,3,0
3,3,290.13,0.0,0.0,90,1,19,2012-10-02 12:00:00,5026,2012,10,2,12,1,0,0,0,0
4,3,291.14,0.0,0.0,75,1,2,2012-10-02 13:00:00,4918,2012,10,2,13,1,0,0,0,0

In [27]:
# Optional: Verify the integrated data

print("Integrated dataset preview:")
display(df_integrated.head())

print("\nIntegrated dataset info:")
print(df_integrated.info())

Integrated dataset preview:

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume,year,month,day,hour,day_of_week,is_weekend,is_rush_hour,part_of_day,season
0,3,288.28,0.0,0.0,40,1,24,2012-10-02 09:00:00,5545,2012,10,2,9,1,0,1,3,0
1,3,289.36,0.0,0.0,75,1,2,2012-10-02 10:00:00,4516,2012,10,2,10,1,0,0,3,0
2,3,289.58,0.0,0.0,90,1,19,2012-10-02 11:00:00,4767,2012,10,2,11,1,0,0,3,0
3,3,290.13,0.0,0.0,90,1,19,2012-10-02 12:00:00,5026,2012,10,2,12,1,0,0,0,0
4,3,291.14,0.0,0.0,75,1,2,2012-10-02 13:00:00,4918,2012,10,2,13,1,0,0,0,0

Integrated dataset info:
<class 'pandas.DataFrame'>
Index: 48187 entries, 0 to 48203
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   holiday              48187 non-null  int64
 1   temp                 48187 non-null  float64
 2   rain_1h              48187 non-null  float64
 3   snow_1h              48187 non-null  float64
 4   clouds_all           48187 non-null  int64
 5   weather_main         48187 non-null  int64
 6   weather_description  48187 non-null  int64
 7   date_time            48187 non-null  datetime64[us]
 8   traffic_volume       48187 non-null  int64
 9   year                 48187 non-null  int32
 10  month                48187 non-null  int32
 11  day                  48187 non-null  int32
 12  hour                 48187 non-null  int32
 13  day_of_week          48187 non-null  int32
 14  is_weekend           48187 non-null  int64
 15  is_rush_hour         48187 non-null  int64
 16  part_of_day          48187 non-null  int64
 17  season               48187 non-null  int64
dtypes: datetime64[us](1), float64(3), int32(5), int64(9)
memory usage: 6.1 MB
None

---
### Task 5: Format Data

This final preparation task ensures the data is in the correct format for the modelling tools. Activities include:

- **Data Type Conversions:** Ensure all columns have appropriate data types (e.g., numeric, datetime, categorical).
- **Column Reordering:** Arrange columns in a logical order (e.g., features first, target last).
- **Renaming:** Give columns clear, descriptive names.
- **Saving the Prepared Dataset:** Export the final, clean dataset for use in subsequent phases.

**Instructions:** Apply any final formatting changes and save the prepared dataset.

In [36]:
# Apply final formatting — data types, column order, renaming

df_final = df_integrated.copy()

# Drop raw datetime after feature engineering
if "date_time" in df_final.columns:
    df_final = df_final.drop(columns=["date_time"])

# Convert boolean dummy columns to integers if needed
bool_cols = df_final.select_dtypes(include="bool").columns
for col in bool_cols:
    df_final[col] = df_final[col].astype(int)

# Ensure key engineered integer columns are int
int_cols = [
    "traffic_volume", "year", "month", "day", "hour",
    "day_of_week", "is_weekend", "is_rush_hour"
]

for col in int_cols:
    if col in df_final.columns:
        df_final[col] = df_final[col].astype(int)

print("Final formatting completed.")
print("Final dataset shape:", df_final.shape)
print("Final columns:")
print(df_final.columns.tolist())

display(df_final.head())

Final formatting completed.
Final dataset shape: (48187, 17)
Final columns:
['holiday', 'temp', 'rain_1h', 'snow_1h', 'clouds_all', 'weather_main', 'weather_description', 'traffic_volume', 'year', 'month', 'day', 'hour', 'day_of_week', 'is_weekend', 'is_rush_hour', 'part_of_day', 'season']

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,traffic_volume,year,month,day,hour,day_of_week,is_weekend,is_rush_hour,part_of_day,season
0,3,288.28,0.0,0.0,40,1,24,5545,2012,10,2,9,1,0,1,3,0
1,3,289.36,0.0,0.0,75,1,2,4516,2012,10,2,10,1,0,0,3,0
2,3,289.58,0.0,0.0,90,1,19,4767,2012,10,2,11,1,0,0,3,0
3,3,290.13,0.0,0.0,90,1,19,5026,2012,10,2,12,1,0,0,0,0
4,3,291.14,0.0,0.0,75,1,2,4918,2012,10,2,13,1,0,0,0,0

In [37]:
# TODO: Verify the final prepared dataset.

print("-" * 60)
print("FINAL PREPARED DATASET SUMMARY")
print("-" * 60)
print(f"Shape: {df_final.shape}")
print(f"Missing values: {df_final.isnull().sum().sum()}")
print(f"Duplicates: {df_final.duplicated().sum()}")

print("\nColumn types:")
print(df_final.dtypes)

print("\nFirst 5 rows:")
display(df_final.head())

print("\nPhase 3 Summary Insight:")
print("- The dataset has now been cleaned, transformed, and engineered for modelling.")
print("- Raw datetime information has been converted into useful time-based features.")
print("- The prepared dataset is ready to be used directly in Phase 4 without repeating preprocessing steps.")

------------------------------------------------------------
FINAL PREPARED DATASET SUMMARY
------------------------------------------------------------
Shape: (48187, 17)
Missing values: 0
Duplicates: 0

Column types:
holiday                  int64
temp                   float64
rain_1h                float64
snow_1h                float64
clouds_all               int64
weather_main             int64
weather_description      int64
traffic_volume           int64
year                     int64
month                    int64
day                      int64
hour                     int64
day_of_week              int64
is_weekend               int64
is_rush_hour             int64
part_of_day              int64
season                   int64
dtype: object

First 5 rows:

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,traffic_volume,year,month,day,hour,day_of_week,is_weekend,is_rush_hour,part_of_day,season
0,3,288.28,0.0,0.0,40,1,24,5545,2012,10,2,9,1,0,1,3,0
1,3,289.36,0.0,0.0,75,1,2,4516,2012,10,2,10,1,0,0,3,0
2,3,289.58,0.0,0.0,90,1,19,4767,2012,10,2,11,1,0,0,3,0
3,3,290.13,0.0,0.0,90,1,19,5026,2012,10,2,12,1,0,0,0,0
4,3,291.14,0.0,0.0,75,1,2,4918,2012,10,2,13,1,0,0,0,0

Phase 3 Summary Insight:
- The dataset has now been cleaned, transformed, and engineered for modelling.
- Raw datetime information has been converted into useful time-based features.
- The prepared dataset is ready to be used directly in Phase 4 without repeating preprocessing steps.

In [30]:
# TODO: Save the prepared dataset for use in Phase 4 (Modelling).


OUTPUT_PATH = "../data/traffic_volume_prepared.csv"   # change if needed
df_final.to_csv(OUTPUT_PATH, index=False)

print(f"Prepared dataset saved to: {OUTPUT_PATH}")

Prepared dataset saved to: ../data/traffic_volume_prepared.csv